### PR TITLE
Dev - Workflow testing

### PR DESCRIPTION
**Pull request by Domodan**
Setting up and testing the workflow done - require a review.

### CODE REVIEW

**Comment by Domodan** [comment]
Waiting for a review

**Comment by dnajjuma** [comment]
Proceed

**Comment by dnajjuma** [comment]
Gjj

**Review by dnajjuma — APPROVED** [review]

**Review by dnajjuma — APPROVED** [review]

**Review by dnajjuma — APPROVED** [review]

**Review by dnajjuma — APPROVED** [review]

**Review by dnajjuma — APPROVED** [review]

**Review by dnajjuma — APPROVED** [review]

**Review by dnajjuma — APPROVED** [review]

**Review by dnajjuma — APPROVED** [review]
..

**Review by dnajjuma — APPROVED** [review]

**Review by dnajjuma — APPROVED** [review]

**Pull request merged**
